/**
 * Detector: category coverage gap.
 *
 * Triggers when:
 *   - last 14 days has ≥ 5 sessions in a category (across all teams)
 *   - that category's overall failure_rate ≥ 25%
 *
 * Generates a P1 suggestion to expand skill / few-shot for that category.
 *
 * Detector ID: D-002-category-coverage-gap
 */

import type { Env } from '../../env'

const DETECTOR_ID = 'D-002-category-coverage-gap'
const DETECTOR_VERSION = 'v1.0'
const FAILURE_THRESHOLD = 0.25
const MIN_SAMPLES = 5
const LOOKBACK_DAYS = 14

interface CategoryRow {
  category_id: string
  category_name: string
  total: number
  failures: number
  refuses: number
  partials: number
}

interface DetectorResult {
  detector_id: string
  problems_found: number
  suggestions_created: number
  suggestions_skipped: number
}

export async function detectCategoryCoverageGap(env: Env): Promise<DetectorResult> {
  const db = env.DB

  const problems = await db.prepare(
    `SELECT
        qc.category_id,
        c.name AS category_name,
        COUNT(*) AS total,
        SUM(CASE WHEN se.success_label = 'failure' THEN 1 ELSE 0 END) AS failures,
        SUM(CASE WHEN se.success_label = 'refuse' THEN 1 ELSE 0 END) AS refuses,
        SUM(CASE WHEN se.success_label = 'partial' THEN 1 ELSE 0 END) AS partials
     FROM int_sessions_enriched se
     JOIN int_question_classifications qc
       ON qc.session_id = se.session_id AND qc.server_id = se.server_id AND qc.is_primary = 1
     JOIN int_taxonomy_categories c ON c.category_id = qc.category_id
     WHERE se.enriched_at >= datetime('now', ?)
     GROUP BY qc.category_id
     HAVING total >= ?
        AND (failures + refuses + partials) * 1.0 / total >= ?`,
  ).bind(`-${LOOKBACK_DAYS} days`, MIN_SAMPLES, FAILURE_THRESHOLD).all<CategoryRow>()

  let created = 0
  let skipped = 0

  for (const p of problems.results) {
    const result = await createSuggestion(env, p)
    if (result === 'created') created++
    else skipped++
  }

  return {
    detector_id: DETECTOR_ID,
    problems_found: problems.results.length,
    suggestions_created: created,
    suggestions_skipped: skipped,
  }
}

async function createSuggestion(env: Env, p: CategoryRow): Promise<'created' | 'skipped'> {
  const db = env.DB
  const badCount = p.failures + p.refuses + p.partials
  const badRate = badCount / p.total
  const dedupKey = `${DETECTOR_ID}:cat=${p.category_id}:open`

  const existing = await db.prepare(
    `SELECT 1 FROM int_optimization_suggestions
     WHERE dedup_key = ? AND status NOT IN ('rejected', 'obsolete', 'rolled_back')`,
  ).bind(dedupKey).first()
  if (existing) return 'skipped'

  const suggestionId = `S-${ymd()}-${randHex()}`
  const title = `分类「${p.category_name}」全平台不达标率 ${(badRate * 100).toFixed(0)}%`
  const description = `过去 ${LOOKBACK_DAYS} 天，「${p.category_name}」分类共 ${p.total} 条会话，其中 ${p.failures} 失败 / ${p.refuses} 拒答 / ${p.partials} 部分回答，整体不达标率 ${(badRate * 100).toFixed(1)}%。这是跨团队普遍现象，说明 skill / context 在该领域有系统性缺口。`
  const rootCause = `当前 Attribuly skill 对该类问题的覆盖可能不足。常见原因：(1) skill prompt 缺少该场景的 few-shot；(2) Attribuly API 在该数据维度返回不完整；(3) 路由规则把该类问题误派给次优 skill。`
  const action = `1. 抽取该分类下 10 条失败/部分回答样本，人工 review；2. 识别共性缺失（数据字段 / 答案格式 / 推理深度）；3. 给 Attribuly skill 加 few-shot 并验证；4. 上线后观察 30 天该分类成功率变化。`

  await db.prepare(
    `INSERT INTO int_optimization_suggestions
      (suggestion_id, type, title, description, root_cause, suggested_action,
       priority, track,
       scope_team_ids, scope_category_ids, affected_sessions,
       estimated_success_delta,
       generated_by, generator_version, source_signal,
       status, dedup_key)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'open', ?)`,
  ).bind(
    suggestionId, 'coverage_gap', title, description, rootCause, action,
    'P1', 'manual',
    'all', p.category_id, badCount,
    0.15,
    `system_${DETECTOR_ID}`, DETECTOR_VERSION, 'category_coverage_gap',
    dedupKey,
  ).run()

  await db.prepare(
    `INSERT INTO int_suggestion_evidence
      (suggestion_id, evidence_kind, snapshot_json, note)
     VALUES (?, 'metric', ?, ?)`,
  ).bind(
    suggestionId,
    JSON.stringify({
      category_id: p.category_id,
      total: p.total,
      failures: p.failures,
      refuses: p.refuses,
      partials: p.partials,
      bad_rate: badRate,
      lookback_days: LOOKBACK_DAYS,
    }),
    `Aggregate stats over last ${LOOKBACK_DAYS} days`,
  ).run()

  await db.prepare(
    `INSERT INTO int_suggestion_comments
      (suggestion_id, author_id, body, action, metadata_json)
     VALUES (?, 'system', ?, 'created', ?)`,
  ).bind(
    suggestionId,
    `Auto-generated by ${DETECTOR_ID} (${DETECTOR_VERSION}). Bad rate ${(badRate * 100).toFixed(1)}% over ${p.total} sessions.`,
    JSON.stringify({ bad_rate: badRate, threshold: FAILURE_THRESHOLD, total: p.total }),
  ).run()

  return 'created'
}

function ymd(): string {
  return new Date().toISOString().slice(0, 10).replace(/-/g, '')
}

function randHex(): string {
  return Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, '0')
}
