/**
 * Detector: high failure rate per (team, category).
 *
 * Triggers when:
 *   - team has ≥ 3 sessions in a primary L1 category in last 14 days
 *   - failure_rate (failure + refuse) ≥ 30%
 *
 * Generates a manual P1 suggestion with up to 5 sample session IDs as evidence.
 *
 * Detector ID: D-001-high-failure-category (used in dedup_key)
 */

import type { Env } from '../../env'

const DETECTOR_ID = 'D-001-high-failure-category'
const DETECTOR_VERSION = 'v1.0'
const FAILURE_THRESHOLD = 0.30
const MIN_SAMPLES = 3
const LOOKBACK_DAYS = 14

interface ProblemRow {
  team_id: string
  category_id: string
  category_name: string
  total: number
  failures: number
  refuses: number
}

interface DetectorResult {
  detector_id: string
  problems_found: number
  suggestions_created: number
  suggestions_skipped: number
}

export async function detectHighFailureCategory(env: Env): Promise<DetectorResult> {
  const db = env.DB

  const problems = await db.prepare(
    `SELECT
        se.team_id,
        qc.category_id,
        c.name AS category_name,
        COUNT(*) AS total,
        SUM(CASE WHEN se.success_label = 'failure' THEN 1 ELSE 0 END) AS failures,
        SUM(CASE WHEN se.success_label = 'refuse' THEN 1 ELSE 0 END) AS refuses
     FROM int_sessions_enriched se
     JOIN int_question_classifications qc
       ON qc.session_id = se.session_id
      AND qc.server_id = se.server_id
      AND qc.is_primary = 1
     JOIN int_taxonomy_categories c ON c.category_id = qc.category_id
     WHERE se.enriched_at >= datetime('now', ?)
     GROUP BY se.team_id, qc.category_id
     HAVING total >= ?
        AND (failures + refuses) * 1.0 / total >= ?`,
  ).bind(`-${LOOKBACK_DAYS} days`, MIN_SAMPLES, FAILURE_THRESHOLD).all<ProblemRow>()

  let created = 0
  let skipped = 0

  for (const p of problems.results) {
    const result = await createSuggestion(env, p)
    if (result === 'created') created++
    else skipped++
  }

  return {
    detector_id: DETECTOR_ID,
    problems_found: problems.results.length,
    suggestions_created: created,
    suggestions_skipped: skipped,
  }
}

async function createSuggestion(env: Env, p: ProblemRow): Promise<'created' | 'skipped'> {
  const db = env.DB
  const failureRate = (p.failures + p.refuses) / p.total
  const dedupKey = `${DETECTOR_ID}:team=${p.team_id}:cat=${p.category_id}:open`
  const suggestionId = `S-${ymd()}-${randHex()}`

  // Check dedup
  const existing = await db.prepare(
    `SELECT suggestion_id FROM int_optimization_suggestions
     WHERE dedup_key = ? AND status NOT IN ('rejected', 'obsolete', 'rolled_back')`,
  ).bind(dedupKey).first()
  if (existing) return 'skipped'

  const title = `Team ${p.team_id} 在「${p.category_name}」分类失败率 ${(failureRate * 100).toFixed(0)}%`
  const description = `过去 ${LOOKBACK_DAYS} 天内，team ${p.team_id} 提的「${p.category_name}」类问题共 ${p.total} 条，其中 ${p.failures} 条失败、${p.refuses} 条被拒答，整体失败率 ${(failureRate * 100).toFixed(1)}%（阈值 ${(FAILURE_THRESHOLD * 100).toFixed(0)}%）。`
  const rootCause = `规则判定失败：可能原因包括 (1) 该团队在此领域有特殊术语 / 数据结构未被覆盖；(2) 当前 skill 缺少处理这类问题的 few-shot；(3) 上游 Attribuly API 返回数据不完整。需要人工 review 样本对话。`
  const action = `1. 抽取 5-10 条样本对话人工 review；2. 识别共性失败模式；3. 视情况：(a) 扩充该团队的 skill personalization、(b) 补充 few-shot、(c) 反馈给 Attribuly API 团队。`

  await db.prepare(
    `INSERT INTO int_optimization_suggestions
      (suggestion_id, type, title, description, root_cause, suggested_action,
       priority, track,
       scope_team_ids, scope_category_ids, affected_sessions,
       estimated_success_delta,
       generated_by, generator_version, source_signal,
       status, dedup_key)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'open', ?)`,
  ).bind(
    suggestionId, 'failure_cluster', title, description, rootCause, action,
    'P1', 'manual',
    p.team_id, p.category_id, p.failures + p.refuses,
    0.10,                                       // conservative estimate
    `system_${DETECTOR_ID}`, DETECTOR_VERSION, 'failure_rate_high',
    dedupKey,
  ).run()

  // Attach sample sessions as evidence
  await attachSampleEvidence(env, suggestionId, p.team_id, p.category_id)

  // System comment marking creation
  await db.prepare(
    `INSERT INTO int_suggestion_comments
       (suggestion_id, author_id, body, action, metadata_json)
     VALUES (?, 'system', ?, 'created', ?)`,
  ).bind(
    suggestionId,
    `Auto-generated by ${DETECTOR_ID} (${DETECTOR_VERSION}). Failure rate ${(failureRate * 100).toFixed(1)}% over ${p.total} sessions.`,
    JSON.stringify({ failure_rate: failureRate, threshold: FAILURE_THRESHOLD, total: p.total }),
  ).run()

  return 'created'
}

async function attachSampleEvidence(env: Env, suggestionId: string, teamId: string, categoryId: string): Promise<void> {
  const samples = await env.DB.prepare(
    `SELECT se.session_id, se.server_id, se.success_label, se.success_conf,
            se.total_duration_ms, se.tool_call_count
     FROM int_sessions_enriched se
     JOIN int_question_classifications qc
       ON qc.session_id = se.session_id AND qc.server_id = se.server_id
      AND qc.is_primary = 1
     WHERE se.team_id = ?
       AND qc.category_id = ?
       AND se.success_label IN ('failure', 'refuse')
     ORDER BY se.enriched_at DESC LIMIT 5`,
  ).bind(teamId, categoryId).all()

  for (const s of samples.results) {
    await env.DB.prepare(
      `INSERT INTO int_suggestion_evidence
        (suggestion_id, evidence_kind, reference_type, reference_id, snapshot_json, note)
       VALUES (?, 'session_sample', 'session', ?, ?, ?)`,
    ).bind(
      suggestionId,
      `${(s as { server_id: string }).server_id}/${(s as { session_id: string }).session_id}`,
      JSON.stringify(s),
      `Failure sample: ${(s as { success_label: string }).success_label}`,
    ).run()
  }
}

function ymd(): string {
  return new Date().toISOString().slice(0, 10).replace(/-/g, '')
}

function randHex(): string {
  return Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, '0')
}
